import sqlite3
connect = sqlite3.Connection('python_bus')
curser = connect.cursor()

# curser.execute("create table Bus(busID int primary key,bustype varchar(20),capacity int,fare int ,opid int,rid int,constraint busfk foreign key(opid) references operator(operatorid));")
# curser.execute("create table operator(operatorid int primary key,op_name varchar(15),address varchar(30),phonenumber int,email varchar(30));")
# curser.execute("create table route(routeid int,sid int,sname varchar(20),primary key(routeid,sid));")
# curser.execute("drop table bookinghistory")
# curser.execute(" create table runs(busid int,date varchar(12),availability int,primary key(busid,date), constraint runsfk foreign key(busid) references bus(busid));")
# # curser.execute('drop table bookinghistory')
# curser.execute('create table bookinghistory(mobileno int ,name varchar(15),gender varchar(10),seats int,age int,bid int,datebook varchar(12),boardingp varchar(15),destination varchar(15),farepaid int,bookingref Integer primary key autoincrement,nameop varchar(15),constraint bookfk foreign key(bid) references bus(busid))')
# # curser.execute('delete from bookinghistory where bookingref = 1')
# # curser.execute("alter table runs add primary key(busid,date)")
# curser.execute('insert into bus(busid,bustype,capacity,fare,opid,rid) values (1,"AC 2x2",30,1000,1,1),(2,"Non AC 2x2",40,500,1,1),(3,"AC-Sleeper 2x1",20,1500,2,2);')
# curser.execute('insert into operator(operatorid,op_name,address,phonenumber,email) values (3,"volvowala","ad street,delhi",1234567,"volvo@gmail.com"),(4,"buswale","b road,jodhpur",123354545,"buswale@gmail.com");')
# curser.execute(' insert into route(routeid,sid,sname) values (1,1,"guna"),(1,2,"jaypee colledge"),(1,3,"biaora"),(1,4,"binagunj"),(1,5,"bhopal");')
# curser.execute(' insert into route(routeid,sid,sname) values (2,1,"bhopal"),(2,2,"binagunj"),(2,3,"biaora"),(2,4,"jaypee colledge"),(2,5,"guna");')
# curser.execute(' insert into runs(busid,date,availability) values (1,"29/11/2022",30),(2,"29/11/2022",40),(3,"29/11/2022",20);')
# curser.execute(' insert into runs(busid,date,availability) values (1,"30/11/2022",30),(2,"30/11/2022",40),(3,"30/11/2022",20);')
# curser.execute('insert into runs(busid,date,availability) values (1,"1/12/2022",30),(2,"1/12/2022",40),(3,"1/12/2022",20);')
# connect.commit()
# curser.execute("alter table bus add constraint busfk foreign key (opid) references operator(operatorid);")

# curser.execute("select * from bus")
# res =curser.fetchall()
# curser.execute("select * from operator")
# res1 = curser.fetchall()
# # print(res1)
# # curser.execute("select * from runs")
# # curser.execute("describe  runs")
# res2 = curser.fetchall()
# # print(res2)
# curser.execute("select * from route")
# res3 = curser.fetchall()
# # print(res3)
# # print(res)
# curser.execute("select busid from bus")
# b =  curser.fetchall()
# # print(b)
# curser.execute("select * from bus;")
# c = curser.fetchall()
# # print(c)

# connect.close()
curser.execute('select busid from bus where opid = 3')
van = curser.fetchall()
print(van)